/**
 * @file
 * @brief Reset module IDs for nuvoton m45x
 */

/*
 * Copyright (c) 2024 Nuvoton Technology Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_RESET_NUMICRO_M45X_RESET_H_
#define ZEPHYR_INCLUDE_DT_BINDINGS_RESET_NUMICRO_M45X_RESET_H_

/* Beginning of M451 BSP sys_reg.h reset module copy */

#define NUMICRO_SYS_IPRST0_CHIPRST_Pos   0
#define NUMICRO_SYS_IPRST0_CPURST_Pos    1
#define NUMICRO_SYS_IPRST0_PDMARST_Pos   2
#define NUMICRO_SYS_IPRST0_EBIRST_Pos    3
#define NUMICRO_SYS_IPRST0_USBHRST_Pos   4
#define NUMICRO_SYS_IPRST0_CRCRST_Pos    7

#define NUMICRO_SYS_IPRST1_GPIORST_Pos   1
#define NUMICRO_SYS_IPRST1_TMR0RST_Pos   2
#define NUMICRO_SYS_IPRST1_TMR1RST_Pos   3
#define NUMICRO_SYS_IPRST1_TMR2RST_Pos   4
#define NUMICRO_SYS_IPRST1_TMR3RST_Pos   5
#define NUMICRO_SYS_IPRST1_ACMP01RST_Pos 7
#define NUMICRO_SYS_IPRST1_I2C0RST_Pos   8
#define NUMICRO_SYS_IPRST1_I2C1RST_Pos   9
#define NUMICRO_SYS_IPRST1_SPI0RST_Pos   12
#define NUMICRO_SYS_IPRST1_SPI1RST_Pos   13
#define NUMICRO_SYS_IPRST1_SPI2RST_Pos   14
#define NUMICRO_SYS_IPRST1_UART0RST_Pos  16
#define NUMICRO_SYS_IPRST1_UART1RST_Pos  17
#define NUMICRO_SYS_IPRST1_UART2RST_Pos  18
#define NUMICRO_SYS_IPRST1_UART3RST_Pos  19
#define NUMICRO_SYS_IPRST1_CAN0RST_Pos   24
#define NUMICRO_SYS_IPRST1_OTGRST_Pos    26
#define NUMICRO_SYS_IPRST1_USBDRST_Pos   27
#define NUMICRO_SYS_IPRST1_EADCRST_Pos   28

#define NUMICRO_SYS_IPRST2_SC0RST_Pos    0
#define NUMICRO_SYS_IPRST2_DACRST_Pos    12
#define NUMICRO_SYS_IPRST2_PWM0RST_Pos   16
#define NUMICRO_SYS_IPRST2_PWM1RST_Pos   17
#define NUMICRO_SYS_IPRST2_TKRST_Pos     25

/* End of M451 BSP sys_reg.h reset module copy */

#define NUMICRO_RST_ID_IPRST0 (0UL << 24)
#define NUMICRO_RST_ID_IPRST1 (4UL << 24)
#define NUMICRO_RST_ID_IPRST2 (8UL << 24)

/* Module Reset Control Register constant definitions. */

#define NUMICRO_PDMA_RST   (NUMICRO_RST_ID_IPRST0 | NUMICRO_SYS_IPRST0_PDMARST_Pos)
#define NUMICRO_EBI_RST    (NUMICRO_RST_ID_IPRST0 | NUMICRO_SYS_IPRST0_EBIRST_Pos)
#define NUMICRO_USBH_RST   (NUMICRO_RST_ID_IPRST0 | NUMICRO_SYS_IPRST0_USBHRST_Pos)
#define NUMICRO_CRC_RST    (NUMICRO_RST_ID_IPRST0 | NUMICRO_SYS_IPRST0_CRCRST_Pos)

#define NUMICRO_GPIO_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_GPIORST_Pos)
#define NUMICRO_TMR0_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_TMR0RST_Pos)
#define NUMICRO_TMR1_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_TMR1RST_Pos)
#define NUMICRO_TMR2_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_TMR2RST_Pos)
#define NUMICRO_TMR3_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_TMR3RST_Pos)
#define NUMICRO_ACMP01_RST (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_ACMP01RST_Pos)
#define NUMICRO_I2C0_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_I2C0RST_Pos)
#define NUMICRO_I2C1_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_I2C1RST_Pos)
#define NUMICRO_SPI0_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_SPI0RST_Pos)
#define NUMICRO_SPI1_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_SPI1RST_Pos)
#define NUMICRO_SPI2_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_SPI2RST_Pos)
#define NUMICRO_UART0_RST  (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_UART0RST_Pos)
#define NUMICRO_UART1_RST  (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_UART1RST_Pos)
#define NUMICRO_UART2_RST  (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_UART2RST_Pos)
#define NUMICRO_UART3_RST  (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_UART3RST_Pos)
#define NUMICRO_CAN0_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_CAN0RST_Pos)
#define NUMICRO_OTG_RST    (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_OTGRST_Pos)
#define NUMICRO_USBD_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_USBDRST_Pos)
#define NUMICRO_EADC_RST   (NUMICRO_RST_ID_IPRST1 | NUMICRO_SYS_IPRST1_EADCRST_Pos)

#define NUMICRO_SC0_RST    (NUMICRO_RST_ID_IPRST2 | NUMICRO_SYS_IPRST2_SC0RST_Pos)
#define NUMICRO_DAC_RST    (NUMICRO_RST_ID_IPRST2 | NUMICRO_SYS_IPRST2_DACRST_Pos)
#define NUMICRO_PWM0_RST   (NUMICRO_RST_ID_IPRST2 | NUMICRO_SYS_IPRST2_PWM0RST_Pos)
#define NUMICRO_PWM1_RST   (NUMICRO_RST_ID_IPRST2 | NUMICRO_SYS_IPRST2_PWM1RST_Pos)
#define NUMICRO_TK_RST     (NUMICRO_RST_ID_IPRST2 | NUMICRO_SYS_IPRST2_TKRST_Pos)

/* End of M451 BSP sys.h reset module copy */

#endif /* ZEPHYR_INCLUDE_DT_BINDINGS_RESET_NUMICRO_M45X_RESET_H_ */
