/*
 * Copyright (c) 2024 Nuvoton Technology Corporation.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_NUMAKER_M45X_CLOCK_H
#define ZEPHYR_INCLUDE_DT_BINDINGS_CLOCK_NUMAKER_M45X_CLOCK_H

/* Beginning of M451 BSP clk_reg.h copy */

#define NUMAKER_CLK_AHBCLK_PDMACKEN_Pos          (1)
#define NUMAKER_CLK_AHBCLK_ISPCKEN_Pos           (2)
#define NUMAKER_CLK_AHBCLK_EBICKEN_Pos           (3)
#define NUMAKER_CLK_AHBCLK_USBHCKEN_Pos          (4)
#define NUMAKER_CLK_AHBCLK_CRCCKEN_Pos           (7)
#define NUMAKER_CLK_AHBCLK_FMCIDLE_Pos           (15)

#define NUMAKER_CLK_APBCLK0_WDTCKEN_Pos          (0)
#define NUMAKER_CLK_APBCLK0_RTCCKEN_Pos          (1)
#define NUMAKER_CLK_APBCLK0_TMR0CKEN_Pos         (2)
#define NUMAKER_CLK_APBCLK0_TMR1CKEN_Pos         (3)
#define NUMAKER_CLK_APBCLK0_TMR2CKEN_Pos         (4)
#define NUMAKER_CLK_APBCLK0_TMR3CKEN_Pos         (5)
#define NUMAKER_CLK_APBCLK0_CLKOCKEN_Pos         (6)
#define NUMAKER_CLK_APBCLK0_ACMP01CKEN_Pos       (7)
#define NUMAKER_CLK_APBCLK0_I2C0CKEN_Pos         (8)
#define NUMAKER_CLK_APBCLK0_I2C1CKEN_Pos         (9)
#define NUMAKER_CLK_APBCLK0_SPI0CKEN_Pos         (12)
#define NUMAKER_CLK_APBCLK0_SPI1CKEN_Pos         (13)
#define NUMAKER_CLK_APBCLK0_SPI2CKEN_Pos         (14)
#define NUMAKER_CLK_APBCLK0_UART0CKEN_Pos        (16)
#define NUMAKER_CLK_APBCLK0_UART1CKEN_Pos        (17)
#define NUMAKER_CLK_APBCLK0_UART2CKEN_Pos        (18)
#define NUMAKER_CLK_APBCLK0_UART3CKEN_Pos        (19)
#define NUMAKER_CLK_APBCLK0_CAN0CKEN_Pos         (24)
#define NUMAKER_CLK_APBCLK0_OTGCKEN_Pos          (26)
#define NUMAKER_CLK_APBCLK0_USBDCKEN_Pos         (27)
#define NUMAKER_CLK_APBCLK0_EADCCKEN_Pos         (28)

#define NUMAKER_CLK_APBCLK1_SC0CKEN_Pos          (0)
#define NUMAKER_CLK_APBCLK1_DACCKEN_Pos          (12)
#define NUMAKER_CLK_APBCLK1_PWM0CKEN_Pos         (16)
#define NUMAKER_CLK_APBCLK1_PWM1CKEN_Pos         (17)
#define NUMAKER_CLK_APBCLK1_TKCKEN_Pos           (25)

#define NUMAKER_CLK_CLKSEL0_HCLKSEL_Pos          (0)
#define NUMAKER_CLK_CLKSEL0_STCLKSEL_Pos         (3)
#define NUMAKER_CLK_CLKSEL0_PCLK0SEL_Pos         (6)
#define NUMAKER_CLK_CLKSEL0_PCLK1SEL_Pos         (7)

#define NUMAKER_CLK_CLKSEL1_WDTSEL_Pos           (0)
#define NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos          (8)
#define NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos          (12)
#define NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos          (16)
#define NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos          (20)
#define NUMAKER_CLK_CLKSEL1_UARTSEL_Pos          (24)
#define NUMAKER_CLK_CLKSEL1_CLKOSEL_Pos          (28)
#define NUMAKER_CLK_CLKSEL1_WWDTSEL_Pos          (30)

#define NUMAKER_CLK_CLKSEL2_PWM0SEL_Pos          (0)
#define NUMAKER_CLK_CLKSEL2_PWM1SEL_Pos          (1)
#define NUMAKER_CLK_CLKSEL2_SPI0SEL_Pos          (2)
#define NUMAKER_CLK_CLKSEL2_SPI1SEL_Pos          (4)
#define NUMAKER_CLK_CLKSEL2_SPI2SEL_Pos          (6)

#define NUMAKER_CLK_CLKSEL3_SC0SEL_Pos           (0)
#define NUMAKER_CLK_CLKSEL3_RTCSEL_Pos           (8)

#define NUMAKER_CLK_CLKDIV0_HCLKDIV_Pos          (0)
#define NUMAKER_CLK_CLKDIV0_USBDIV_Pos           (4)
#define NUMAKER_CLK_CLKDIV0_UARTDIV_Pos          (8)
#define NUMAKER_CLK_CLKDIV0_EADCDIV_Pos          (16)

#define NUMAKER_CLK_CLKDIV1_SC0DIV_Pos           (0)

/* End of M451 BSP clk_reg.h copy */

/* Beginning of M451 BSP clk.h copy */

/*  CLKSEL0 constant definitions.  (Write-protection) */
#define NUMAKER_CLK_CLKSEL0_HCLKSEL_HXT  (0x0UL << NUMAKER_CLK_CLKSEL0_HCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_HCLKSEL_LXT  (0x1UL << NUMAKER_CLK_CLKSEL0_HCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_HCLKSEL_PLL  (0x2UL << NUMAKER_CLK_CLKSEL0_HCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_HCLKSEL_LIRC (0x3UL << NUMAKER_CLK_CLKSEL0_HCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_HCLKSEL_HIRC (0x7UL << NUMAKER_CLK_CLKSEL0_HCLKSEL_Pos)

#define NUMAKER_CLK_CLKSEL0_STCLKSEL_HXT       (0x0UL << NUMAKER_CLK_CLKSEL0_STCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_STCLKSEL_LXT       (0x1UL << NUMAKER_CLK_CLKSEL0_STCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_STCLKSEL_HXT_DIV2  (0x2UL << NUMAKER_CLK_CLKSEL0_STCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_STCLKSEL_HCLK_DIV2 (0x3UL << NUMAKER_CLK_CLKSEL0_STCLKSEL_Pos)
#define NUMAKER_CLK_CLKSEL0_STCLKSEL_HIRC_DIV2 (0x7UL << NUMAKER_CLK_CLKSEL0_STCLKSEL_Pos)

#define NUMAKER_CLK_CLKSEL0_PCLK0SEL_HCLK      (0x0UL << NUMAKER_CLK_CLKSEL0_PCLK0SEL_Pos)
#define NUMAKER_CLK_CLKSEL0_PCLK0SEL_HCLK_DIV2 (0x1UL << NUMAKER_CLK_CLKSEL0_PCLK0SEL_Pos)

#define NUMAKER_CLK_CLKSEL0_PCLK1SEL_HCLK      (0x0UL << NUMAKER_CLK_CLKSEL0_PCLK1SEL_Pos)
#define NUMAKER_CLK_CLKSEL0_PCLK1SEL_HCLK_DIV2 (0x1UL << NUMAKER_CLK_CLKSEL0_PCLK1SEL_Pos)

/*  CLKSEL1 constant definitions. */
#define NUMAKER_CLK_CLKSEL1_WDTSEL_LXT          (0x1UL << NUMAKER_CLK_CLKSEL1_WDTSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_WDTSEL_LIRC         (0x3UL << NUMAKER_CLK_CLKSEL1_WDTSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_WDTSEL_HCLK_DIV2048 (0x2UL << NUMAKER_CLK_CLKSEL1_WDTSEL_Pos)

#define NUMAKER_CLK_CLKSEL1_TMR0SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR0SEL_LXT   (0x1UL << NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR0SEL_LIRC  (0x5UL << NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR0SEL_HIRC  (0x7UL << NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR0SEL_PCLK0 (0x2UL << NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR0SEL_EXT   (0x3UL << NUMAKER_CLK_CLKSEL1_TMR0SEL_Pos)

#define NUMAKER_CLK_CLKSEL1_TMR1SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR1SEL_LXT   (0x1UL << NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR1SEL_LIRC  (0x5UL << NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR1SEL_HIRC  (0x7UL << NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR1SEL_PCLK0 (0x2UL << NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR1SEL_EXT   (0x3UL << NUMAKER_CLK_CLKSEL1_TMR1SEL_Pos)

#define NUMAKER_CLK_CLKSEL1_TMR2SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR2SEL_LXT   (0x1UL << NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR2SEL_LIRC  (0x5UL << NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR2SEL_HIRC  (0x7UL << NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR2SEL_PCLK1 (0x2UL << NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR2SEL_EXT   (0x3UL << NUMAKER_CLK_CLKSEL1_TMR2SEL_Pos)

#define NUMAKER_CLK_CLKSEL1_TMR3SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR3SEL_LXT   (0x1UL << NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR3SEL_LIRC  (0x5UL << NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR3SEL_HIRC  (0x7UL << NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR3SEL_PCLK1 (0x2UL << NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos)
#define NUMAKER_CLK_CLKSEL1_TMR3SEL_EXT   (0x3UL << NUMAKER_CLK_CLKSEL1_TMR3SEL_Pos)

/* M451: All UARTs share a single clock selector UARTSEL */
#define NUMAKER_CLK_CLKSEL1_UARTSEL_HXT  (0x0UL << NUMAKER_CLK_CLKSEL1_UARTSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_UARTSEL_PLL  (0x1UL << NUMAKER_CLK_CLKSEL1_UARTSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_UARTSEL_LXT  (0x2UL << NUMAKER_CLK_CLKSEL1_UARTSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_UARTSEL_HIRC (0x3UL << NUMAKER_CLK_CLKSEL1_UARTSEL_Pos)

#define NUMAKER_CLK_CLKSEL1_CLKOSEL_HXT  (0x0UL << NUMAKER_CLK_CLKSEL1_CLKOSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_CLKOSEL_LXT  (0x1UL << NUMAKER_CLK_CLKSEL1_CLKOSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_CLKOSEL_HIRC (0x3UL << NUMAKER_CLK_CLKSEL1_CLKOSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_CLKOSEL_HCLK (0x2UL << NUMAKER_CLK_CLKSEL1_CLKOSEL_Pos)

#define NUMAKER_CLK_CLKSEL1_WWDTSEL_LIRC         (0x3UL << NUMAKER_CLK_CLKSEL1_WWDTSEL_Pos)
#define NUMAKER_CLK_CLKSEL1_WWDTSEL_HCLK_DIV2048 (0x2UL << NUMAKER_CLK_CLKSEL1_WWDTSEL_Pos)

/*  CLKSEL2 constant definitions. */
#define NUMAKER_CLK_CLKSEL2_PWM0SEL_PLL   (0x0UL << NUMAKER_CLK_CLKSEL2_PWM0SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_PWM0SEL_PCLK0 (0x1UL << NUMAKER_CLK_CLKSEL2_PWM0SEL_Pos)

#define NUMAKER_CLK_CLKSEL2_PWM1SEL_PLL   (0x0UL << NUMAKER_CLK_CLKSEL2_PWM1SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_PWM1SEL_PCLK1 (0x1UL << NUMAKER_CLK_CLKSEL2_PWM1SEL_Pos)

#define NUMAKER_CLK_CLKSEL2_SPI0SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL2_SPI0SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI0SEL_PLL   (0x1UL << NUMAKER_CLK_CLKSEL2_SPI0SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI0SEL_PCLK0 (0x2UL << NUMAKER_CLK_CLKSEL2_SPI0SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI0SEL_HIRC  (0x3UL << NUMAKER_CLK_CLKSEL2_SPI0SEL_Pos)

#define NUMAKER_CLK_CLKSEL2_SPI1SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL2_SPI1SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI1SEL_PLL   (0x1UL << NUMAKER_CLK_CLKSEL2_SPI1SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI1SEL_PCLK1 (0x2UL << NUMAKER_CLK_CLKSEL2_SPI1SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI1SEL_HIRC  (0x3UL << NUMAKER_CLK_CLKSEL2_SPI1SEL_Pos)

#define NUMAKER_CLK_CLKSEL2_SPI2SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL2_SPI2SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI2SEL_PLL   (0x1UL << NUMAKER_CLK_CLKSEL2_SPI2SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI2SEL_PCLK0 (0x2UL << NUMAKER_CLK_CLKSEL2_SPI2SEL_Pos)
#define NUMAKER_CLK_CLKSEL2_SPI2SEL_HIRC  (0x3UL << NUMAKER_CLK_CLKSEL2_SPI2SEL_Pos)

/*  CLKSEL3 constant definitions. */
#define NUMAKER_CLK_CLKSEL3_SC0SEL_HXT   (0x0UL << NUMAKER_CLK_CLKSEL3_SC0SEL_Pos)
#define NUMAKER_CLK_CLKSEL3_SC0SEL_PLL   (0x1UL << NUMAKER_CLK_CLKSEL3_SC0SEL_Pos)
#define NUMAKER_CLK_CLKSEL3_SC0SEL_PCLK0 (0x2UL << NUMAKER_CLK_CLKSEL3_SC0SEL_Pos)
#define NUMAKER_CLK_CLKSEL3_SC0SEL_HIRC  (0x3UL << NUMAKER_CLK_CLKSEL3_SC0SEL_Pos)

#define NUMAKER_CLK_CLKSEL3_RTCSEL_LXT  (0x0UL << NUMAKER_CLK_CLKSEL3_RTCSEL_Pos)
#define NUMAKER_CLK_CLKSEL3_RTCSEL_LIRC (0x1UL << NUMAKER_CLK_CLKSEL3_RTCSEL_Pos)

/* CLKDIV0 constant definitions. */
#define NUMAKER_CLK_CLKDIV0_HCLK(x)  (((x) - 1UL) << NUMAKER_CLK_CLKDIV0_HCLKDIV_Pos)
#define NUMAKER_CLK_CLKDIV0_USB(x)   (((x) - 1UL) << NUMAKER_CLK_CLKDIV0_USBDIV_Pos)
#define NUMAKER_CLK_CLKDIV0_UART(x)  (((x) - 1UL) << NUMAKER_CLK_CLKDIV0_UARTDIV_Pos)
#define NUMAKER_CLK_CLKDIV0_EADC(x)  (((x) - 1UL) << NUMAKER_CLK_CLKDIV0_EADCDIV_Pos)

/* CLKDIV1 constant definitions. */
#define NUMAKER_CLK_CLKDIV1_SC0(x) (((x) - 1UL) << NUMAKER_CLK_CLKDIV1_SC0DIV_Pos)

/*  MODULE constant definitions.
 *
 *  Encoding: APBCLK(31:30)|CLKSEL(29:28)|CLKSEL_Msk(27:25)|CLKSEL_Pos(24:20)|
 *            CLKDIV(19:18)|CLKDIV_Msk(17:10)|CLKDIV_Pos(9:5)|IP_EN_Pos(4:0)
 */

#define NUMAKER_MODULE_NoMsk            0x0UL
#define NUMAKER_NA                      NUMAKER_MODULE_NoMsk

#define NUMAKER_MODULE_APBCLK_ENC(x)        (((x) & 0x03UL) << 30)
#define NUMAKER_MODULE_CLKSEL_ENC(x)        (((x) & 0x03UL) << 28)
#define NUMAKER_MODULE_CLKSEL_Msk_ENC(x)    (((x) & 0x07UL) << 25)
#define NUMAKER_MODULE_CLKSEL_Pos_ENC(x)    (((x) & 0x1fUL) << 20)
#define NUMAKER_MODULE_CLKDIV_ENC(x)        (((x) & 0x03UL) << 18)
#define NUMAKER_MODULE_CLKDIV_Msk_ENC(x)    (((x) & 0xffUL) << 10)
#define NUMAKER_MODULE_CLKDIV_Pos_ENC(x)    (((x) & 0x1fUL) <<  5)
#define NUMAKER_MODULE_IP_EN_Pos_ENC(x)     (((x) & 0x1fUL) <<  0)

/* AHBCLK */
#define NUMAKER_PDMA_MODULE      ((0UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(1UL<<0))
#define NUMAKER_ISP_MODULE       ((0UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(2UL<<0))
#define NUMAKER_EBI_MODULE       ((0UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(3UL<<0))
#define NUMAKER_USBH_MODULE      ((0UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(0UL<<18)|(0x0FUL<<10)|(4UL<<5)|(4UL<<0))
#define NUMAKER_CRC_MODULE       ((0UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(7UL<<0))
#define NUMAKER_FMCIDLE_MODULE   ((0UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(15UL<<0))

/* APBCLK0 */
#define NUMAKER_WDT_MODULE       ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(0UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(0UL<<0))
#define NUMAKER_WWDT_MODULE      ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(30UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(0UL<<0))
#define NUMAKER_RTC_MODULE       ((1UL<<30)|(3UL<<28)|(0x1UL<<25)|(8UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(1UL<<0))
#define NUMAKER_TMR0_MODULE      ((1UL<<30)|(1UL<<28)|(0x7UL<<25)|(8UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(2UL<<0))
#define NUMAKER_TMR1_MODULE      ((1UL<<30)|(1UL<<28)|(0x7UL<<25)|(12UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(3UL<<0))
#define NUMAKER_TMR2_MODULE      ((1UL<<30)|(1UL<<28)|(0x7UL<<25)|(16UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(4UL<<0))
#define NUMAKER_TMR3_MODULE      ((1UL<<30)|(1UL<<28)|(0x7UL<<25)|(20UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(5UL<<0))
#define NUMAKER_CLKO_MODULE      ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(28UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(6UL<<0))
#define NUMAKER_ACMP01_MODULE    ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(7UL<<0))
#define NUMAKER_I2C0_MODULE      ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(8UL<<0))
#define NUMAKER_I2C1_MODULE      ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(9UL<<0))
#define NUMAKER_SPI0_MODULE      ((1UL<<30)|(2UL<<28)|(0x3UL<<25)|(2UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(12UL<<0))
#define NUMAKER_SPI1_MODULE      ((1UL<<30)|(2UL<<28)|(0x3UL<<25)|(4UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(13UL<<0))
#define NUMAKER_SPI2_MODULE      ((1UL<<30)|(2UL<<28)|(0x3UL<<25)|(6UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(14UL<<0))
/* M451: All UARTs share CLKSEL1_UARTSEL(bits 25:24) and CLKDIV0_UARTDIV(bits 11:8) */
#define NUMAKER_UART0_MODULE     ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(24UL<<20)|(0UL<<18)|(0x0FUL<<10)|(8UL<<5)|(16UL<<0))
#define NUMAKER_UART1_MODULE     ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(24UL<<20)|(0UL<<18)|(0x0FUL<<10)|(8UL<<5)|(17UL<<0))
#define NUMAKER_UART2_MODULE     ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(24UL<<20)|(0UL<<18)|(0x0FUL<<10)|(8UL<<5)|(18UL<<0))
#define NUMAKER_UART3_MODULE     ((1UL<<30)|(1UL<<28)|(0x3UL<<25)|(24UL<<20)|(0UL<<18)|(0x0FUL<<10)|(8UL<<5)|(19UL<<0))
#define NUMAKER_CAN0_MODULE      ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(24UL<<0))
#define NUMAKER_OTG_MODULE       ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(0UL<<18)|(0x0FUL<<10)|(4UL<<5)|(26UL<<0))
#define NUMAKER_USBD_MODULE      ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(0UL<<18)|(0x0FUL<<10)|(4UL<<5)|(27UL<<0))
#define NUMAKER_EADC_MODULE      ((1UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(0UL<<18)|(0xFFUL<<10)|(16UL<<5)|(28UL<<0))

/* APBCLK1 */
#define NUMAKER_SC0_MODULE       ((2UL<<30)|(3UL<<28)|(0x3UL<<25)|(0UL<<20)|(1UL<<18)|(0xFFUL<<10)|(0UL<<5)|(0UL<<0))
#define NUMAKER_DAC_MODULE       ((2UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(12UL<<0))
#define NUMAKER_PWM0_MODULE      ((2UL<<30)|(2UL<<28)|(0x1UL<<25)|(0UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(16UL<<0))
#define NUMAKER_PWM1_MODULE      ((2UL<<30)|(2UL<<28)|(0x1UL<<25)|(1UL<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(17UL<<0))
#define NUMAKER_TK_MODULE        ((2UL<<30)|(NUMAKER_MODULE_NoMsk<<28)|(NUMAKER_MODULE_NoMsk<<25)|(NUMAKER_MODULE_NoMsk<<20)|(NUMAKER_MODULE_NoMsk<<18)|(NUMAKER_MODULE_NoMsk<<10)|(NUMAKER_MODULE_NoMsk<<5)|(25UL<<0))

/* End of M451 BSP clk.h copy */

#endif
